### ISSUE TITLE
Enhancement: 

### ISSUE THREAD

**Issue by lucytoastinne484** [stake2/stake2-website#3]
![Captura de Tela (27)](https://github.com/Stake2/Websites/assets/130234165/590109de-b846-404b-8854-ac57a6a848b8)
![Captura de Tela (26)](https://github.com/Stake2/Websites/assets/130234165/ef4c615d-d3e2-4cf6-8843-f9a066a8b81c)

tem umas coisas que nao tao funcionando no site e assim mesmo?

**Comment by Stake2** [comment]
Esse é o site "Things I Do" ou "Coisas Que Eu Faço", ele está antigo e ainda não foi atualizado
Ele será atualizado em breve
